version: '3'

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_USER: &DATABASE_USER "wordpress"
      DATABASE_PASSWORD: &DATABASE_PASSWORD "wordpress"
      DATABASE_NAME: &DATABASE_NAME "wordpress"
      DATABASE_HOST: &DATABASE_HOST "mysql"
    ports:
      - "8080:80"

  mysql:
    image: mariadb:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "ciscocisco"
      MYSQL_USER: *DATABASE_USER
      MYSQL_PASSWORD: *DATABASE_PASSWORD
      MYSQL_DATABASE: *DATABASE_NAME